"""Central prompt definitions (ARGO Upgrade Plan Section 0)."""

from app.prompts.architecture import (
    SYSTEM_BASE,
    EMAIL_CLASSIFICATION_PROMPT,
    EMAIL_REPLY_PROMPT,
    MORNING_BRIEFING_PROMPT,
    RESEARCH_ANALYSIS_PROMPT,
    MEETING_INTELLIGENCE_PROMPT,
    ECONOMIC_RELEASE_PROMPT,
    WHATSAPP_REPORT_PROMPT,
)

__all__ = [
    "SYSTEM_BASE",
    "EMAIL_CLASSIFICATION_PROMPT",
    "EMAIL_REPLY_PROMPT",
    "MORNING_BRIEFING_PROMPT",
    "RESEARCH_ANALYSIS_PROMPT",
    "MEETING_INTELLIGENCE_PROMPT",
    "ECONOMIC_RELEASE_PROMPT",
    "WHATSAPP_REPORT_PROMPT",
]
