"""OvernightSummary model — daily morning briefings generated by ARGO."""
from __future__ import annotations
from datetime import date, datetime
from typing import Optional

from sqlalchemy import Boolean, Date, DateTime, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, generate_uuid


class OvernightSummary(Base, TimestampMixin):
    """Daily overnight briefing synthesized by ARGO at 03:30 AM London time.

    Covers emails received 22:00–03:30, market data, and financial headlines.
    Delivered via Twilio WhatsApp with email as fallback.
    """
    __tablename__ = "overnight_summaries"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    summary_date: Mapped[date] = mapped_column(Date, nullable=False, unique=True, index=True)
    coverage_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    coverage_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    executive_summary: Mapped[str] = mapped_column(Text, nullable=False)
    email_section: Mapped[str] = mapped_column(Text, nullable=False, default="[]")  # JSON
    market_moves_section: Mapped[str] = mapped_column(Text, nullable=False, default="[]")  # JSON
    news_section: Mapped[str] = mapped_column(Text, nullable=False, default="[]")  # JSON
    macro_section: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    full_briefing_text: Mapped[str] = mapped_column(Text, nullable=False)
    whatsapp_delivered: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    whatsapp_delivered_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    whatsapp_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    email_delivered: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    email_delivered_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    email_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    model_used: Mapped[str] = mapped_column(String(64), nullable=False)
    raw_inputs: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON debug data

    def __repr__(self) -> str:
        return f"<OvernightSummary date={self.summary_date!r} delivered={self.whatsapp_delivered}>"
